import boa
from boa.util.abi import abi_encode
from helpers import etherscan_key, rpc_url, c_args


# Automate: Read the deployed address from the file generated by main.py
try:
    with open("broadcast/deployed_address.txt", "r") as f:
        deployed_address = f.read().strip()
except FileNotFoundError:
    deployed_address = None


def verify():
    if not deployed_address:
        print("No deployed address found in deployed_address.txt")
        return

    boa.set_network_env(rpc_url)

    # 1. Load the contract metadata
    raffle = boa.load_partial("contracts/raffle.vy").at(deployed_address)

    # 2. Encode the constructor arguments manually
    # The schema must match your @deploy __init__ exactly
    ctor_args = abi_encode(
        "(uint256,address)", [c_args.entrance_fee, c_args.vrf_wrapper_address]
    )

    # 3. Attach the arguments to the contract object
    # This ensures boa.verify() picks them up correctly
    raffle.ctor_calldata = ctor_args

    # Use the v2 API URI with chainid included
    # We also pass chain_id separately as required by the Etherscan class
    verifier = boa.explorer.Etherscan(
        uri="https://api.etherscan.io/v2/api",
        api_key=etherscan_key,
        chain_id=11155111,
    )

    # 4. Run verification
    print(f"Verifying contract at {deployed_address} on Sepolia...")
    boa.verify(contract=raffle, verifier=verifier, wait=True)


if __name__ == "__main__":
    verify()
